// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmZQ9L10vsjEWTtq5ktF2hEOs36hVm_dY',
    appId: '1:481823728180:web:f0128861d723b539ce6061',
    messagingSenderId: '481823728180',
    projectId: 'fastconnectapp',
    authDomain: 'fastconnectapp.firebaseapp.com',
    storageBucket: 'fastconnectapp.firebasestorage.app',
    measurementId: 'G-XVM7HRKLT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3N9HcEXptx_pIafcCvtxBxEn10OO2fkQ',
    appId: '1:481823728180:android:84037da83126dfb5ce6061',
    messagingSenderId: '481823728180',
    projectId: 'fastconnectapp',
    storageBucket: 'fastconnectapp.firebasestorage.app',
  );

}