// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint

// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for iOS. '
//           'Run FlutterFire CLI to configure it.',
//         );
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macOS. '
//           'Run FlutterFire CLI to configure it.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for Windows. '
//           'Run FlutterFire CLI to configure it.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for Linux. '
//           'Run FlutterFire CLI to configure it.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDmZQ9L10vsjEWTtq5ktF2hEOs36hVm_dY',
//     appId: '1:481823728180:web:fb3e21cbd0a8f92dce6061',
//     messagingSenderId: '481823728180',
//     projectId: 'fastconnectapp',
//     authDomain: 'fastconnectapp.firebaseapp.com',
//     storageBucket: 'fastconnectapp.firebasestorage.app',
//     measurementId: 'G-BKNY8N6JLE',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyB3N9HcEXptx_pIafcCvtxBxEn10OO2fkQ',
//     appId: '1:481823728180:android:8f096e64574dc7c4ce6061',
//     messagingSenderId: '481823728180',
//     projectId: 'fastconnectapp',
//     storageBucket: 'fastconnectapp.firebasestorage.app',
//   );
// }
